export type ThaiPharmacyBrandRule = {
  brandName: string;
  aliases: readonly string[];
};

/**
 * Curated aliases used for deterministic imports. Keep this list conservative:
 * a missing match is reviewable, while a false match silently corrupts product data.
 */
export const THAI_PHARMACY_BRAND_RULES: readonly ThaiPharmacyBrandRule[] = [
  { brandName: "3M", aliases: ["3m", "nexcare", "เน็กซ์แคร์", "neoplast"] },
  { brandName: "2P", aliases: ["2p", "2p original"] },
  { brandName: "BURAPHA", aliases: ["burapha", "บูรพา"] },
  { brandName: "Unicharm", aliases: ["unicharm", "ยูนิชาร์ม", "ยูนิชาม"] },
  { brandName: "ไทยนคร", aliases: ["ไทยนคร", "thainakorn", "thai nakorn", "thai nakorn patana"] },
  { brandName: "กระต่ายบิน", aliases: ["กระต่ายบิน", "ตรากระต่ายบิน", "flying rabbit"] },
  { brandName: "ระดมพล", aliases: ["ระดมพล", "radompol", "radom pol", "radompon"] },
  { brandName: "ตรางู", aliases: ["ตรางู", "snake brand"] },
  { brandName: "โป๊ยเซียน", aliases: ["โป๊ยเซียน", "poy sian", "poysian"] },
  { brandName: "หงส์ไทย", aliases: ["หงส์ไทย", "hong thai", "hongthai"] },
  { brandName: "เซียงเพียว", aliases: ["เซียงเพียว", "siang pure", "siangpure"] },
  { brandName: "เป๊ปเปอร์มิ้นท์ ฟิลด์", aliases: ["เป๊ปเปอร์มิ้นท์ ฟิลด์", "peppermint field"] },
  { brandName: "ถ้วยทอง", aliases: ["ถ้วยทอง", "golden cup balm"] },
  { brandName: "ห้าเจดีย์", aliases: ["ห้าเจดีย์", "five pagodas"] },
  { brandName: "อ้วยอันโอสถ", aliases: ["อ้วยอัน", "อ้วยอันโอสถ", "ouay un"] },
  { brandName: "ขาวละออ", aliases: ["ขาวละออ", "khaolaor", "khao la or"] },
  { brandName: "ซากุระโค่ย", aliases: ["ซากุระโค่ย", "sakura koi"] },
  { brandName: "BIOTHYMUS", aliases: ["biothymus", "biothymus-m"] },
  { brandName: "Zambuk", aliases: ["zambuk", "แซมบัค", "แซมบั๊ค"] },
  { brandName: "Tiger Balm", aliases: ["tiger balm", "ยาหม่องตราเสือ", "ตราเสือ"] },
  { brandName: "Counterpain", aliases: ["counterpain", "เคาน์เตอร์เพน"] },
  { brandName: "Vicks", aliases: ["vicks", "วิคส์"] },
  { brandName: "Durex", aliases: ["durex", "ดูเร็กซ์"] },
  { brandName: "Dettol", aliases: ["dettol", "เดทตอล"] },
  { brandName: "Betadine", aliases: ["betadine", "เบตาดีน"] },
  { brandName: "Tylenol", aliases: ["tylenol", "ไทลินอล"] },
  { brandName: "Panadol", aliases: ["panadol", "พานาดอล"] },
  { brandName: "Sara", aliases: ["sara", "ซาร่า"] },
  { brandName: "Tiffy", aliases: ["tiffy", "ทิฟฟี่"] },
  { brandName: "Decolgen", aliases: ["decolgen", "ดีคอลเจน"] },
  { brandName: "Strepsils", aliases: ["strepsils", "สเตร็ปซิล"] },
  { brandName: "Zyrtec", aliases: ["zyrtec", "เซอร์เทค"] },
  { brandName: "Clarityne", aliases: ["clarityne", "คลาริทีน"] },
  { brandName: "Allegra", aliases: ["allegra", "อัลเลกรา"] },
  { brandName: "Gaviscon", aliases: ["gaviscon", "กาวิสคอน"] },
  { brandName: "Air-X", aliases: ["air-x", "air x", "แอร์เอ็กซ์"] },
  { brandName: "ENO", aliases: ["eno", "อีโน"] },
  { brandName: "Buscopan", aliases: ["buscopan", "บัสโคพาน"] },
  { brandName: "Imodium", aliases: ["imodium", "อิมโมเดียม"] },
  { brandName: "Smecta", aliases: ["smecta", "สเม็คต้า"] },
  { brandName: "Bioflor", aliases: ["bioflor", "ไบโอฟลอร์"] },
  { brandName: "Dulcolax", aliases: ["dulcolax", "ดัลโคแลกซ์"] },
  { brandName: "Senokot", aliases: ["senokot", "เซโนคอต"] },
  { brandName: "Voltaren", aliases: ["voltaren", "โวลทาเรน"] },
  { brandName: "Hirudoid", aliases: ["hirudoid", "ฮีรูดอยด์"] },
  { brandName: "Hiruscar", aliases: ["hiruscar", "ฮีรูสการ์"] },
  { brandName: "Burnova", aliases: ["burnova", "เบอร์โนว่า"] },
  { brandName: "Klean & Kare", aliases: ["klean & kare", "klean and kare", "คลีนแอนด์แคร์"] },
  { brandName: "Smooth E", aliases: ["smooth e", "สมูทอี"] },
  { brandName: "Provamed", aliases: ["provamed", "โปรวาเมด"] },
  { brandName: "MizuMi", aliases: ["mizumi", "มิซูมิ"] },
  { brandName: "Eucerin", aliases: ["eucerin", "ยูเซอริน"] },
  { brandName: "Cetaphil", aliases: ["cetaphil", "เซตาฟิล"] },
  { brandName: "CeraVe", aliases: ["cerave", "เซราวี"] },
  { brandName: "Physiogel", aliases: ["physiogel", "ฟิซิโอเจล"] },
  { brandName: "La Roche-Posay", aliases: ["la roche-posay", "la roche posay", "ลา โรช-โพเซย์"] },
  { brandName: "Bioderma", aliases: ["bioderma", "ไบโอเดอร์มา"] },
  { brandName: "NIVEA", aliases: ["nivea", "นีเวีย"] },
  { brandName: "Johnson's", aliases: ["johnson's", "johnsons", "จอห์นสัน"] },
  { brandName: "Babi Mild", aliases: ["babi mild", "เบบี้มายด์"] },
  { brandName: "Kodomo", aliases: ["kodomo", "โคโดโม"] },
  { brandName: "Sensodyne", aliases: ["sensodyne", "เซ็นโซดายน์"] },
  { brandName: "Parodontax", aliases: ["parodontax", "พาโรดอนแทกซ์"] },
  { brandName: "Dentiste", aliases: ["dentiste", "เดนทิสเต้"] },
  { brandName: "Systema", aliases: ["systema", "ซิสเท็มมา"] },
  { brandName: "Colgate", aliases: ["colgate", "คอลเกต"] },
  { brandName: "Oral-B", aliases: ["oral-b", "oral b", "ออรัลบี"] },
  { brandName: "Listerine", aliases: ["listerine", "ลิสเตอรีน"] },
  { brandName: "Blackmores", aliases: ["blackmores", "แบลคมอร์ส"] },
  { brandName: "Vistra", aliases: ["vistra", "วิสทร้า"] },
  { brandName: "Mega We Care", aliases: ["mega we care", "เมก้า วีแคร์"] },
  { brandName: "Centrum", aliases: ["centrum", "เซนทรัม"] },
  { brandName: "Berocca", aliases: ["berocca", "เบอรอคค่า"] },
  { brandName: "BRAND'S", aliases: ["brand's", "brands", "แบรนด์"] },
  { brandName: "Scott's", aliases: ["scott's", "scotts", "สก๊อต"] },
  { brandName: "Ensure", aliases: ["ensure", "เอนชัวร์"] },
  { brandName: "Glucerna", aliases: ["glucerna", "กลูเซอร์นา"] },
] as const;
